services:
  # 백엔드 API 서버
  - type: web
    name: smart-voice-guard-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    repo: https://github.com/yonghwan1106/smart_voice_guard.git
    branch: master
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: smart-voice-guard-db
          property: connectionString
    healthCheckPath: /health

  # 프론트엔드 정적 사이트
  - type: web
    name: smart-voice-guard-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    rootDir: frontend
    repo: https://github.com/yonghwan1106/smart_voice_guard.git
    branch: master
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://smart-voice-guard-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  # PostgreSQL 데이터베이스 (90일 무료)
  - name: smart-voice-guard-db
    databaseName: smart_voice_guard
    user: smart_voice_guard_user
    plan: free